name: Build and Test

on:
  push:
    branches: [ "main", "dev", "master" ]
  pull_request:
    branches: [ "main", "dev", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dotnet SDK 
        uses: actions/setup-dotnet@v3 
        with: 
          dotnet-version: '8.0' #SDK Version to use 
          
      - name: Try to build my code 
        run: dotnet build

      - name: Run unit tests on my code 
        run: dotnet test -v n
